"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
export function ReviewerReviewForm({requestId,status,reviewerId,currentUserId,dueAt}:{requestId:string;status:string;reviewerId:string|null;currentUserId:string;dueAt:string|null}){
 const router=useRouter(); const [claimed,setClaimed]=useState(status==="claimed"&&reviewerId===currentUserId); const [deadline,setDeadline]=useState(dueAt); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
 async function claim(){setLoading(true);setMessage("");const supabase=createClient();const {data,error}=await supabase.rpc("claim_review",{selected_request:requestId});if(error||!data){setMessage(error?.message??"This review was already claimed by another reviewer.");setLoading(false);return}setClaimed(true);setDeadline(new Date(Date.now()+48*60*60*1000).toISOString());setLoading(false);router.refresh()}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage("");const form=new FormData(event.currentTarget);const {error}=await createClient().rpc("complete_review",{selected_request:requestId,feedback_strengths:String(form.get("strengths")),feedback_improvements:String(form.get("improvements")),feedback_recommendations:String(form.get("jobTips")),feedback_summary:String(form.get("summary"))});if(error){setMessage(error.message);setLoading(false);return}router.refresh()}
 if(!claimed)return <div className="claim-panel"><p className="eyebrow">Available review</p><h2>Claim this candidate</h2><p>Starting locks the request to your account for 48 hours. If the deadline passes, it returns to the company queue automatically.</p>{message&&<p className="form-error">{message}</p>}<button className="button button-primary button-block" onClick={claim} disabled={loading}>{loading?"Claiming...":"Start review"}</button></div>;
 return <form className="review-form" onSubmit={submit}><div className="deadline-banner"><div><span className="eyebrow">Structured feedback</span><h2>Help this candidate improve</h2></div>{deadline&&<span><strong>Due</strong>{new Date(deadline).toLocaleString()}</span>}</div><p>Be specific, constructive, and relevant to the company’s hiring expectations.</p><label>Overall summary<textarea name="summary" required minLength={30} placeholder="Give the candidate a concise overview..." /></label><label>What is working<textarea name="strengths" required minLength={30} placeholder="Call out credible strengths and effective sections..." /></label><label>What should improve<textarea name="improvements" required minLength={30} placeholder="Give clear edits and explain why they matter..." /></label><label>Company-specific job tips<textarea name="jobTips" required minLength={30} placeholder="Share practical application or interview context..." /></label><div className="payment-note"><span>£</span><p><strong>£1.00 earning</strong> is recorded automatically when this review is completed.</p></div>{message&&<p className="form-error">{message}</p>}<button className="button button-primary button-block" disabled={loading}>{loading?"Submitting...":"Submit completed review"}</button></form>
}
